export type UserRole = 'owner' | 'manager' | 'salesperson' | 'super_admin'
export type BillStatus = 'completed' | 'voided'
export type PaymentMode = 'cash' | 'upi' | 'card' | 'credit'
export type GstScheme = 'regular' | 'composition'
export type StockStatus = 'healthy' | 'low' | 'out'
export type SupplierPaymentMode = 'cash' | 'upi' | 'bank_transfer' | 'cheque' | 'card'
export type CashRegisterStatus = 'open' | 'closed'
export type PurchaseStatus = 'completed'
export type POStatus = 'draft' | 'sent' | 'partial' | 'received' | 'cancelled'
export type AdjustmentReason = 'damage' | 'theft' | 'count_correction' | 'write_off'
export type AuditAction = 'create' | 'update' | 'delete' | 'void'
export type EntityType =
  | 'bill'
  | 'purchase'
  | 'product'
  | 'customer'
  | 'supplier'
  | 'user'
  | 'settings'
  | 'expense'
  | 'purchase_order'
export type TenantStatus = 'active' | 'suspended' | 'trial' | 'expired'
export type SubscriptionPlan = 'free' | 'basic' | 'pro'
export type ReportType =
  | 'daily-sales'
  | 'sales-by-category'
  | 'sales-by-salesperson'
  | 'inventory-valuation'
  | 'low-stock'
  | 'outstanding-payables'
  | 'outstanding-receivables'
  | 'customer-ledger'
  | 'supplier-ledger'
  | 'cash-register'
  | 'pnl'
  | 'purchase-summary'
  | 'expense'
  | 'gst-summary'
  | 'bargain-discount'
  | 'aging-inventory'
  | 'dead-stock'
