export const CONSTANTS = {
  PAGINATION: { DEFAULT_LIMIT: 50 },
  DEBOUNCE: { SEARCH_MS: 300 },
  POS: {
    BARCODE_RAPID_KEYSTROKE_MS: 50,
    BARCODE_SCAN_TIMEOUT_MS: 3000,
  },
  DISCOUNT: {
    GREEN_MAX: 20,
    AMBER_MAX: 30,
  },
  OFFLINE: {
    CATALOG_REFRESH_INTERVAL_MS: 5 * 60 * 1000,
    MAX_OFFLINE_BILLS: 100,
  },
  TOAST_DURATION_MS: 3000,
  PARKED_BILL_EXPIRY_HOURS: 24,
} as const;
